export const NUM_OF_GUESSES_ALLOWED = 6;
export const KEYBOARD_STATUS = {
  Q: "unused",
  W: "unused",
  E: "unused",
  R: "unused",
  T: "unused",
  Y: "unused",
  U: "unused",
  I: "unused",
  O: "unused",
  P: "unused",
  A: "unused",
  S: "unused",
  D: "unused",
  F: "unused",
  G: "unused",
  H: "unused",
  J: "unused",
  K: "unused",
  L: "unused",
  Z: "unused",
  X: "unused",
  C: "unused",
  V: "unused",
  B: "unused",
  N: "unused",
  M: "unused",
};
