export const NUM_OF_GUESSES_ALLOWED = 6;
export const QWERTY_KEYBOARD = [
  ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
  ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
  ["Z", "X", "C", "V", "B", "N", "M"],
];
export const KEYBOARD_STATUS = {
  Q: "unused",
  W: "unused",
  E: "unused",
  R: "unused",
  T: "unused",
  Y: "unused",
  U: "unused",
  I: "unused",
  O: "unused",
  P: "unused",
  A: "unused",
  S: "unused",
  D: "unused",
  F: "unused",
  G: "unused",
  H: "unused",
  J: "unused",
  K: "unused",
  L: "unused",
  Z: "unused",
  X: "unused",
  C: "unused",
  V: "unused",
  B: "unused",
  N: "unused",
  M: "unused",
};
